import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The sidebar is generated from the docs/ folder structure. Ordering comes from
// each page's `sidebar_position` front matter and the `_category_.json` files.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
