/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/scrape-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scrape From Url
         * @description Scrape recipe data from a URL using the scrape_me method.
         *
         *     Example:
         *     ```
         *     {
         *         "url": "https://www.allrecipes.com/recipe/123456/example-recipe/"
         *     }
         *     ```
         */
        post: operations["scrape_from_url_scrape_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scrape-html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scrape From Html
         * @description Scrape recipe data from HTML content using the scrape_html method.
         *
         *     Example:
         *     ```
         *     {
         *         "url": "https://www.allrecipes.com/recipe/123456/example-recipe/",
         *         "html": "<html>...</html>"
         *     }
         *     ```
         */
        post: operations["scrape_from_html_scrape_html_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo-response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Demo Response */
        get: operations["get_demo_response_demo_response_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HtmlRequest */
        HtmlRequest: {
            /** Url */
            url: string;
            /** Html */
            html: string;
        };
        /**
         * IngredientGroup
         * @description Model for grouped ingredients
         */
        IngredientGroup: {
            /**
             * Purpose
             * @description The purpose or name of this ingredient group
             */
            purpose?: string | null;
            /**
             * Ingredients
             * @description List of ingredients in this group
             */
            ingredients?: string[];
        };
        /**
         * RecipeResponse
         * @description Typed model for recipe data
         */
        RecipeResponse: {
            /**
             * Author
             * @description Recipe author name
             */
            author: string;
            /**
             * Canonicalurl
             * @description Canonical URL of the recipe
             */
            canonicalUrl: string;
            /**
             * Category
             * @description Recipe category (e.g., Dessert, Main Course)
             */
            category?: string | null;
            /**
             * Cooktime
             * @description Cooking time in minutes
             */
            cookTime?: number | null;
            /**
             * Cookingmethod
             * @description The method of cooking the recipe
             */
            cookingMethod?: string | null;
            /**
             * Cuisine
             * @description Cuisine type (e.g., Italian, French)
             */
            cuisine?: string | null;
            /**
             * Description
             * @description Recipe description
             */
            description?: string | null;
            /**
             * Dietaryrestrictions
             * @description List of dietary restrictions (e.g., Vegan, Gluten-Free)
             */
            dietaryRestrictions?: string[] | null;
            /**
             * Equipment
             * @description List of equipment needed for the recipe
             */
            equipment?: string[] | null;
            /**
             * Host
             * @description Host domain of the recipe
             */
            host: string;
            /**
             * Image
             * @description URL of the recipe image
             */
            image?: string | null;
            /**
             * Ingredientgroups
             * @description Grouped ingredients
             */
            ingredientGroups: components["schemas"]["IngredientGroup"][];
            /**
             * Ingredients
             * @description List of all ingredients
             */
            ingredients?: string[] | null;
            /**
             * Instructions
             * @description Recipe instructions as a single string
             */
            instructions: string;
            /**
             * Instructionslist
             * @description Recipe instructions as a list of steps
             */
            instructionsList: string[];
            /**
             * Keywords
             * @description List of keywords associated with the recipe
             */
            keywords?: string[] | null;
            /**
             * Language
             * @description Language code (e.g., 'en', 'fr')
             */
            language?: string | null;
            /**
             * Links
             * @description List of links related to the recipe
             */
            links?: {
                [key: string]: string;
            }[];
            /**
             * Nutrients
             * @description Nutritional information
             */
            nutrients?: {
                [key: string]: string;
            };
            /**
             * Preptime
             * @description Preparation time in minutes
             */
            prepTime?: number | null;
            /**
             * Ratings
             * @description Average rating score
             */
            ratings?: number | null;
            /**
             * Ratingscount
             * @description Number of ratings
             */
            ratingsCount?: number | null;
            /**
             * Sitename
             * @description Name of the recipe site
             */
            siteName?: string | null;
            /**
             * Title
             * @description Recipe title
             */
            title?: string | null;
            /**
             * Totaltime
             * @description Total time in minutes
             */
            totalTime?: number | null;
            /**
             * Yields
             * @description Recipe yield (e.g., '4 servings', '1 cake')
             */
            yields?: string | null;
        };
        /** UrlRequest */
        UrlRequest: {
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    scrape_from_url_scrape_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UrlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scrape_from_html_scrape_html_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HtmlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_demo_response_demo_response_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
        };
    };
}
