import type { Metadata, Viewport } from "next";

import { generateAppleWebAppSplashScreenConfigs } from "@/lib/pwa/ios-startup-images";
import { siteConfig } from "@/config/site";

export const appMetadata: Metadata = {
  title: {
    default: siteConfig.name,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  manifest: "/manifest.webmanifest", // auto-generated by app/manifest.ts
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-96x96.png", sizes: "96x96", type: "image/png" },
      { url: "/android-chrome-192x192.png", sizes: "192x192", type: "image/png" },
      { url: "/android-chrome-512x512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
    shortcut: "/favicon.ico",
  },
  appleWebApp: {
    capable: true,
    title: siteConfig.name,
    statusBarStyle: "black-translucent",
    startupImage: generateAppleWebAppSplashScreenConfigs(),
  },
  other: {
    "apple-mobile-web-app-capable": "yes",
  },
  applicationName: siteConfig.name,
};

export const appViewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#336640" },
    { media: "(prefers-color-scheme: light)", color: "#fffef7" },
  ],
  interactiveWidget: "resizes-visual",
};
