name: Docker Build Test

on:
  pull_request:
    branches:
      - main
      - "rc/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-build:
    uses: ./.github/workflows/_docker-build.yml
    secrets: inherit
    with:
      image-tags: norish:test
